# Generated by Django 4.0.4 on 2022-06-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='additions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commit',
            name='deletions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
