# Generated by Django 4.0.4 on 2022-05-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0003_alter_repository_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
