# Generated by Django 4.0.4 on 2022-05-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0005_alter_organization_name_alter_repository_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
