# Generated by Django 4.0.4 on 2022-05-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0006_alter_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
