# Generated by Django 4.0.4 on 2022-05-15 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0007_alter_repository_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('create_at', models.DateTimeField()),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='repos.repository')),
            ],
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=50, unique=True)),
                ('date', models.DateTimeField()),
                ('email', models.CharField(max_length=50)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commit', to='repos.branch')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commit', to='repos.repository')),
            ],
        ),
    ]
